# .github/workflows/deploy.yml
name: Build & Deploy (Astro + manifest)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write  # needed to push to gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci || npm i

      - name: Generate manifest & indexes
        env:
            R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
            R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
            R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
            R2_BUCKET: ${{ secrets.R2_BUCKET }}
            PUBLIC_MEDIA_BASE: ${{ secrets.PUBLIC_MEDIA_BASE }}
            # Optional:
            # R2_OBJECTS_CACHE: data/r2_objects.json
            # R2_SKIP_LIST: '0'
        run: node scripts/generate-manifest.js

      - name: Build site
        run: npx astro build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
